# ベースになる PHP イメージを作成
FROM php:8.0-fpm as base

RUN apt-get update \
    && apt-get install -y zlib1g-dev libzip-dev libpng-dev mariadb-client git ffmpeg \
    && docker-php-ext-install pcntl zip pdo_mysql gd

# Composer install
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

ENV COMPOSER_ALLOW_SUPERUSER 1
ENV COMPOSER_HOME /composer
ENV PATH $PATH:/composer/vendor/bin

# Add user for laravel application -> then assign default to www
# RUN groupadd -g 1000 www
# RUN useradd -u 1000 -ms /bin/sh -g www www

# # Change current user to www
# USER www

WORKDIR /var/www
COPY . /var/www

RUN composer install \
    && chmod -R 777 storage \
    && chmod 777 bootstrap

CMD ["php-fpm"]
