name: CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    name: Install and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: copy env
        run: cp .env.example .env