name: CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    name: Install and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: copy env
        run: cp .env.example .env

      - name: start docker and composer install
        shell: bash
        run: |
          docker-compose build
          docker-compose up -d app
          docker-compose exec -T app composer install

      - name: database migration
        uses: nick-invision/retry@v2
        with:
          retry_wait_seconds: 10
          max_attempts: 3
          timeout_minutes: 1
          shell: bash
          command: docker-compose exec -T app php artisan migrate:fresh --seed

      - name: phpunit
        env:
          SPEC_GITHUB_TOKEN: ${{ secrets.SPEC_GITHUB_TOKEN }}
        run: docker-compose exec -e SPEC_GITHUB_TOKEN=$(echo $SPEC_GITHUB_TOKEN) -T app composer test

      - name: test after phpunit
        shell: bash
        run: |
          docker-compose up -d app
          docker-compose exec -T app composer install

      - name: test coverage
        env:
          SPEC_GITHUB_TOKEN: ${{ secrets.SPEC_GITHUB_TOKEN }}
        run: docker-compose exec -e SPEC_GITHUB_TOKEN=$(echo $SPEC_GITHUB_TOKEN) -T app composer test:coverage

  slack-notify:
    if: always()
    needs: [build]
    name: workflow notification to slack
    runs-on: ubuntu-latest
    steps:
      - uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
